-- Yan_Mod
-- Author: HaoJun0823
-- DateCreated: 8/9/2025 7:11:32 PM
-- Logic: 仅当 Civilization 存在于数据库时插入 Player 定义
--------------------------------------------------------------

-- 1. 插入玩家基础定义
INSERT OR IGNORE INTO Players    
(
    Domain, CivilizationType, LeaderType, 
    CivilizationName, CivilizationIcon, 
    LeaderName, LeaderIcon, 
    CivilizationAbilityName, CivilizationAbilityDescription, CivilizationAbilityIcon, 
    LeaderAbilityName, LeaderAbilityDescription, LeaderAbilityIcon, 
    Portrait, PortraitBackground
)
SELECT 
    'Players:Expansion2_Players', 'CIVILIZATION_OP_YAN', 'LEADER_RANDERION_ARK_WANQING_RED', 
    'LOC_CIVILIZATION_OP_YAN_NAME', 'ICON_CIVILIZATION_OP_YAN', 
    'LOC_LEADER_RANDERION_ARK_WANQING_NAME', 'ICON_LEADER_RANDERION_ARK_WANQING_RED', 
    'LOC_TRAIT_CIVILIZATION_EVERGREEN_NAME', 'LOC_TRAIT_CIVILIZATION_EVERGREEN_DESCRIPTION', 'ICON_CIVILIZATION_OP_YAN', 
    'LOC_TRAIT_LEADER_RANDERION_ARK_WANQING_NAME', 'LOC_TRAIT_LEADER_RANDERION_ARK_WANQING_DESCRIPTION', 'ICON_LEADER_RANDERION_ARK_WANQING_RED', 
    'LEADER_RANDERION_ARK_WANQING_NETRUAL_PREGAME_SMALL', 'Bg_sui_WQ'
WHERE EXISTS (SELECT 1 FROM Players WHERE CivilizationType = 'CIVILIZATION_OP_YAN');

-- 2. 插入特色单位、建筑等项目
INSERT OR IGNORE INTO PlayerItems    
(
    Domain, CivilizationType, LeaderType, 
    Type, Icon, Name, Description, SortIndex
)
SELECT 'Players:Expansion2_Players', 'CIVILIZATION_OP_YAN', 'LEADER_RANDERION_ARK_WANQING_RED', Type, Icon, Name, Description, SortIndex
FROM (
    SELECT 'DISTRICT_JUDICIAL_OFFICE' AS Type, 'ICON_DISTRICT_JUDICIAL_OFFICE' AS Icon, 'LOC_DISTRICT_JUDICIAL_OFFICE_NAME' AS Name, 'LOC_DISTRICT_JUDICIAL_OFFICE_DESCRIPTION' AS Description, 30 AS SortIndex UNION ALL
    SELECT 'IMPROVEMENT_GREAT_WALL', 'ICON_IMPROVEMENT_GREAT_WALL', 'LOC_IMPROVEMENT_GREAT_WALL_NAME', 'LOC_IMPROVEMENT_GREAT_WALL_DESCRIPTION', 40 UNION ALL
    SELECT 'UNIT_CHUN_QIAN', 'ICON_UNIT_CHUN_QIAN', 'LOC_UNIT_CHUN_QIAN_NAME', 'LOC_UNIT_CHUN_QIAN_DESCRIPTION', 50 UNION ALL
    SELECT 'UNIT_INTERN_TIANSHI', 'ICON_UNIT_INTERN_TIANSHI', 'LOC_UNIT_INTERN_TIANSHI_NAME', 'LOC_UNIT_INTERN_TIANSHI_DESCRIPTION', 10 UNION ALL
    SELECT 'DISTRICT_WAN_QING_SPECIAL', 'ICON_DISTRICT_WANQING_SPECIAL', 'LOC_DISTRICT_WANQING_SPECIAL_NAME', 'LOC_DISTRICT_WANQING_SPECIAL_DESCRIPTION', 20
) AS NewItems
WHERE EXISTS (SELECT 1 FROM Players WHERE CivilizationType = 'CIVILIZATION_OP_YAN');